### ISSUE TITLE
No `copy` property for SymmetricArrayAdapter

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#11]
```
import scid.matvec, std.stdio;

void main() {
    auto m = SymmetricMatrix!double(3);
    m[1, 1] = 2;
    auto x = eval(m + m);
    writeln(typeof(x).stringof);
    writeln(x.pretty);
}
```

Error message:

D:\customd\scid\ops\eval.d(96): Error: no property 'copy' for type 'SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder)'
D:\customd\scid\ops\eval.d(96): Error: no property 'copy' for type 'SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder)'
D:\customd\scid\ops\eval.d(114): Error: template instance scid.ops.eval.evalCopy!(tr,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder)))) error instantiating
D:\customd\scid\ops\eval.d(44):        instantiated from here: evalCopy!(cast(Transpose)false,Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder)))),BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))))
test9.d(6):        instantiated from here: eval!(Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder)))))

**Comment by cristicbz** [comment]
Fixed. There are a lot of specializations missing though, so adding to symmetric matrices is pretty slow right now, will add more as we go.
