### ISSUE TITLE
Unidentified identifier alpha when subtracting SymmetricMatrix from general matrix

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#13]
```
import scid.matvec, std.stdio;

void main() {
    auto mat = SymmetricMatrix!double(3);
    auto mat2 = Matrix!double([[1.0, 2, 3], [4.0, 5, 6], [7.0, 8, 9]]);
    auto res = eval(mat2 - mat);
    writeln(res.toString);
}
```

D:\customd\scid\ops\fallback.d(195): Error: undefined identifier alpha
D:\customd\scid\ops\fallback.d(196): Error: undefined identifier tr, did you mean alias t?
D:\customd\scid\ops\fallback.d(196): Error: undefined identifier source, did you mean alias Source?
D:\customd\scid\ops\fallback.d(196): Error: undefined identifier source, did you mean alias Source?
D:\customd\scid\ops\fallback.d(197): Error: undefined identifier tr, did you mean alias t?
D:\customd\scid\ops\fallback.d(197): Error: undefined identifier source, did you mean alias Source?
D:\customd\scid\ops\fallback.d(197): Error: undefined identifier source, did you mean alias Source?
D:\customd\scid\ops\fallback.d(206): Error: undefined identifier tr, did you mean alias t?
D:\customd\scid\ops\fallback.d(207): Error: undefined identifier alpha
D:\customd\scid\ops\fallback.d(207): Error: undefined identifier source, did you mean alias Source?
D:\customd\scid\ops\eval.d(202): Error: template instance scid.ops.fallback.fallbackScaledAddition!(tr,double,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))) error instantiating
D:\customd\scid\ops\eval.d(179):        instantiated from here: evalScaledAddition!(tr,double,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
D:\customd\scid\ops\eval.d(115):        instantiated from here: evalScaledAddition!(tr,double,Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
D:\customd\scid\ops\eval.d(44):        instantiated from here: evalCopy!(cast(Transpose)false,Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
test9.d(6):        instantiated from here: eval!(Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)))
D:\customd\scid\ops\eval.d(179): Error: template instance scid.ops.eval.evalScaledAddition!(tr,double,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))) error instantiating
D:\customd\scid\ops\eval.d(115):        instantiated from here: evalScaledAddition!(tr,double,Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
D:\customd\scid\ops\eval.d(44):        instantiated from here: evalCopy!(cast(Transpose)false,Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
test9.d(6):        instantiated from here: eval!(Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)))
D:\customd\scid\ops\eval.d(115): Error: template instance scid.ops.eval.evalScaledAddition!(tr,double,Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))) error instantiating
D:\customd\scid\ops\eval.d(44):        instantiated from here: evalCopy!(cast(Transpose)false,Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
test9.d(6):        instantiated from here: eval!(Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)))
D:\customd\scid\ops\eval.d(44): Error: template instance scid.ops.eval.evalCopy!(cast(Transpose)false,Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))) error instantiating
test9.d(6):        instantiated from here: eval!(Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double)))
test9.d(6): Error: template instance scid.ops.eval.eval!(Expression!(op,BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))),Expression!(op,BasicMatrix!(PackedStorage!(SymmetricArrayAdapter!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),triangle,storageOrder))),double))) error instantiating

**Comment by cristicbz** [comment]
Fixed. I'd changed the name of an argument and forgot to change it in one of the static-if branches.
