### ISSUE TITLE
unable to build with latest version of rdmd

### ISSUE THREAD

**Issue by filgood** [cristicbz/scid#15]
Hi,

I just synced the latest version and when I try to build, rdmd crashes with no info (dmd 2.054). Win 7 32-bit. Are there special instructions I should follow to build scid on windows?

thanks, filgood

**Comment by cristicbz** [comment]
Sorry I didn't answer to your previous messages, I'm just really very, very busy with the project. The problem is rdmd, it doesn't work in Windows since the latest release, somebody reported it somewhere. Just do 'dmd -run build.d' .

**Comment by filgood** [comment]
On 28/07/2011 19:58, cristicbz wrote:

> Sorry I didn't answer to your previous messages, I'm just really very, very busy with the project. The problem is rdmd, it doesn't work in Windows since the latest release, somebody reported it somewhere. Just do 'dmd -run build.d' .
> 
> no probs. I prefer you to progress with this project. I'm just very 
> interested in the final results of your work hence keen to test it.

anyway, your efforts are much appreciated!
