### ISSUE TITLE
x.t * x should be symmetric

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#16]
Feel free to close this if there's no feasible way to implement it in your current design, but ideally eval(x.t \* x) where x is any matrix should return a SymmetricMatrix, since the result is always symmetric.

If this is not feasible to implement because a check for it would be too costly in terms of either performance or code complexity, then I wonder if it's worth making a special case function for evaluating x.t \* x, since this operation is used very often in statistics.  (Though this is definitely a low-priority enhancement, not a must-have feature.)

**Comment by cristicbz** [comment]
It would be cool, but this seems impossible right now. Whether or not the left-hand-side and the right-hand-side are the same is runtime information, while the return type needs to be known at compile time. We could certainly have a function that performs the operation, though.
If you want, you can of course write:
auto x = Matrix!double( ... );
SymmetricMatrix!double s = x.t*x;
I could provide an optimization for this case, when the programmer tells us that the result is expected to be symmetric.

**Comment by dsimcha** [comment]
On Fri, Jul 29, 2011 at 4:31 AM, cristicbz <
reply@reply.github.com>wrote:

> It would be cool, but this seems impossible right now. Whether or not the
> left-hand-side and the right-hand-side are the same is runtime information,
> while the return type needs to be known at compile time.

(Smacks self in forehead.)  Good point.

> We could certainly have a function that performs the operation, though.
> If you want, you can of course write:
> auto x = Matrix!double( ... );
> SymmetricMatrix!double s = x.t*x;
> I could provide an optimization for this case, when the programmer tells us
> that the result is expected to be symmetric.

Wouldn't this be overloading by return type,though?  How would this work
under the hood?

**Comment by cristicbz** [comment]
Well, x.t \* x by itself returns an Expression object. Writing:
                    sym[] = x.t \* x;
evaluates to:
                    evalCopy( sym, expr )         where expr = x.t*x
Which could of course check if( expr.lhs.data == expr.rhs.data ). The .data is necessary because lhs and rhs are copies (due to the reference problems).
It would of course be impossible to specialize:
                    sym = eval(x.t \* x).
But without the eval() it's fine.

**Comment by dsimcha** [comment]
The more I think about it, the more I like your sym[] = x.t \* x idea, since any solution w/o user intervention seems infeasible.  If you still think it's doable and have time, go for it.  Again, though, if you have too much on your plate, let me know and we can prioritize and/or I can help out with some stuff.

**Comment by dsimcha** [comment]
I'm resolving this because what I originally suggested is definitely not feasible and what we discussed to replace it already works.
