### ISSUE TITLE
Forward reference error w/ inv

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#19]
The following code produces a cascade of forward reference errors.  It may be a compiler bug, but I don't understand your code well enough yet to tell for sure or file a decent bug report if it is.

BTW, I understand that the inversion stuff is still a work in progress.  Is it worth filing bug reports against it yet, or is it premature?

```
import scid.matvec, scid.ops.eval, std.stdio;

void main(string[] args) {
    auto x = Matrix!double([[1.0, 4, 3], [4.0, 5, 6], [7.0, 8, 9]]);
    auto vec = Vector!double([8.0, 2, 3]);
    writeln(eval(inv(x)).pretty);
}
```

c:\customd\scid\ops\eval.d(161): Error: forward reference to inferred return type of function call eval(source,& alloc)
c:\customd\scid\ops\eval.d(70): Error: template instance scid.ops.eval.evalCopy!(cast(Transpose)false,Expression!("inv",BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))),BasicMatrix!(BasicGeneralMatrixViewStorage!(ExternalMatrix!(double,storageOrderOf,RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))) error instantiating
c:\customd\scid\ops\eval.d(161):        instantiated from here: eval!(Expression!("inv",BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))),RegionAllocator)
c:\customd\scid\ops\eval.d(54):        instantiated from here: evalCopy!(cast(Transpose)false,Expression!("inv",BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
C:\code\test.d(6):        instantiated from here: eval!(Expression!("inv",BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))))
c:\customd\scid\ops\eval.d(161): Error: template instance scid.ops.eval.eval!(Expression!("inv",BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))),RegionAllocator) error instantiating
c:\customd\scid\ops\eval.d(54):        instantiated from here: evalCopy!(cast(Transpose)false,Expression!("inv",BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))),BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))))
C:\code\test.d(6):        instantiated from here: eval!(Expression!("inv",BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1)))))

**Comment by cristicbz** [comment]
I guess it's good to have an issue so that we don't forget about it, but right now I only support operations of the form:
Vector = inv(MatrixExpession) \* VectorExpression;
So simply inverting a matrix doesn't work yet.

**Comment by cristicbz** [comment]
I added proper support for matrix inversion in the latest version, this works now.
