### ISSUE TITLE
Matrix/Vector-Scalar Slice-Addition/Subtraction Broken

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#26]
```
import scid.matvec, std.stdio;

void main() {
    auto v = Vector!double([1, 2, 3]);
    v[] -= 5;
 }
```

D:\customd\scid\ops\eval.d(235): Error: static assert  "Incompatible types for addition 'Scalar' and 'ColumnVector'."
D:\customd\scid\vector.d(182):        instantiated from here: evalScaledAddition!(cast(Transpose)false,double,int,BasicVector!(BasicArrayStorage!(RefCounted!(CowArray!(double),cast(RefCountedAutoInitialize)1),vectorType)))
test9.d(5):        instantiated from here: opSliceOpAssign!("-",int)

**Comment by cristicbz** [comment]
This and Issue 27 simply aren't implemented right now, sorry. Trouble is,
there aren't any BLAS calls to do this.
I'll use D's array ops of course, will do it as soon as I get the chance.
On Aug 5, 2011 5:04 AM, "dsimcha" <
reply@reply.github.com>
wrote:

**Comment by dsimcha** [comment]
On 8/5/2011 12:20 AM, cristicbz wrote:

> This and Issue 27 simply aren't implemented right now, sorry. Trouble is,
> there aren't any BLAS calls to do this.
> I'll use D's array ops of course, will do it as soon as I get the chance.

There's nothing whatsoever wrong with using D's array ops instead of 
BLAS.  The array ops are highly optimized and in several cases faster 
than a naive loop.  Don't be afraid to use them.
