### ISSUE TITLE
Recursive Alias Declaration

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#28]
```
import scid.matvec;

alias Vector!double V;
```

scid\storage\array.d(32): Error: alias scid.storage.array.ArrayStorage!(double,vectorType).ArrayStorage recursive alias declaration

**Comment by cristicbz** [comment]
I fixed it, it was very strange, it might be DMD bug. I just disabled a bunch of testing static asserts in storagetraits.d . Will investigate later.
