### ISSUE TITLE
Memory Leak:  Matrix not getting freed

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#30]
This program runs out of memory and produces an access violation.  Apparently for some reason the reference counting scheme is not freeing memory like it should.

```
 import scid.matvec;

 void main() {
     foreach(i; 0..1_000_000) {
         auto mat = Matrix!double(20, 20);
     }
}
```

**Comment by cristicbz** [comment]
This is druntime's fault. I submitted a pull request. You can merge from my
druntime if you want.
On Aug 10, 2011 7:56 PM, "dsimcha" <
reply@reply.github.com>
wrote:

**Comment by dsimcha** [comment]
Ok, found it.  I'll do as you suggested.  Sorry for the noise.

BTW, I'm using SciD for real work today, so far successfully.  Despite all
the bugs that are an unfortunate fact of life when using unstable beta-ish
code, it's quite nice.  The design is extremely well thought out, and it
seems to do exactly what I need, faster and with more readability than the
ad-hoc stuff I would have otherwise written.

**Comment by dsimcha** [comment]
Yep, your suggestion indeed fixes this.  Closing.
