### ISSUE TITLE
Assignment should return value for chaining

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#35]
The following code should work and doesn't:

```
import scid.matvec;

void main() {
    auto mat = Matrix!double(5, 5);
    mat[2, 2] = mat[3, 3] = 5;
}
```

D:\home\dsimcha\bin\test.d(5): Error: function scid.matrix.BasicMatrix!(BasicGeneralMatrixStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1))).BasicMatrix.opIndexAssign (double rhs, uint i, uint j) is not callable using argument types (void,int,int)
D:\home\dsimcha\bin\test.d(5): Error: cannot implicitly convert expression (mat.opIndexAssign(5,3u,3u)) of type void to double

**Comment by cristicbz** [comment]
I know it was assigned to you, but it was so simple, I just decided to do it: https://github.com/cristicbz/scid/commit/48a0752dd6aa85a4c4ceb7a3b02405ac5a32ab9e

**Comment by dsimcha** [comment]
Great.  Wow, I thought there were going to be a lot more places where changes were needed.  I didn't get around to even looking at this before you fixed it b/c I was busy with other stuff.

**Comment by cristicbz** [comment]
Nope, that was the point of the Vector-wraps-Storage design. Storages provide only the smallest needed functionality, while Matrix & Vector provide all the convenience, bells and whistles.

**Comment by dsimcha** [comment]
Well then what can I say?  It's an awesome design even if it took me a while to get its usefulness through my thick head.

**Comment by cristicbz** [comment]
I'm sorry, internet communications are confusing - were you being sarcastic in the previous comment? I hope you didn't get my previous comment the wrong way, I was really just trying to clarify my reasoning. (and please don't say "Sarcastic? Me? Nooooo, of course not." :P)

**Comment by dsimcha** [comment]
No, I wasn't being sarcastic at all.  It was a serious complement.  My point was that this design proved incredibly useful and that before now I hadn't really understood what it was for.  I had kind of wondered until now why you had storage separated from BasicMatrix, etc. like you did but never bothered to ask.  This last commit was a pretty dramatic illustration of the value of this design.
