### ISSUE TITLE
Should be able to assign an array to a column.

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#36]
```
import scid.matvec;

void main() {
    auto mat = Matrix!double(5, 5);
    auto arr = [1.0, 2, 3, 4, 5];
    mat[][3] = arr;
}
```

d:\dmd2\windows\bin....\src\phobos\std\conv.d(4101): Error: function scid.storage.cowmatrix.CowMatrix!(double,order_).CowMatrix.opAssign (CowMatrix!(double,order_) rhs) is not callable using argument types (double[])
d:\dmd2\windows\bin....\src\phobos\std\conv.d(4072): Error: cannot implicitly convert expression (_param_1) of type double[] to CowMatrix!(double,order_)
d:\dmd2\windows\bin....\src\phobos\std\typecons.d(2304): Error: template instance std.conv.emplace!(CowMatrix!(double,order_),double[]) error instantiating
d:\dmd2\windows\bin....\src\phobos\std\typecons.d(2340):        instantiated from here: initialize!(double[])
D:\home\dsimcha\customd\scid\storage\arrayview.d(117):        instantiated from here: __ctor!(double[])
D:\home\dsimcha\customd\scid\vector.d(87):        instantiated from here: __ctor!(double[])
    ... (1 instantiations, -v to show) ...
D:\home\dsimcha\customd\scid\matrix.d(509):        instantiated from here: opSliceAssign!(double[])
D:\home\dsimcha\bin\test.d(6):        instantiated from here: opIndexAssign!(double[])
d:\dmd2\windows\bin....\src\phobos\std\typecons.d(2340): Error: template instance std.typecons.RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1).RefCounted._RefCounted.initialize!(double[]) error instantiating
D:\home\dsimcha\customd\scid\storage\arrayview.d(117):        instantiated from here: __ctor!(double[])
D:\home\dsimcha\customd\scid\vector.d(87):        instantiated from here: __ctor!(double[])
D:\home\dsimcha\customd\scid\vector.d(164):        instantiated from here: __ctor!(double[])
D:\home\dsimcha\customd\scid\matrix.d(509):        instantiated from here: opSliceAssign!(double[])
D:\home\dsimcha\bin\test.d(6):        instantiated from here: opIndexAssign!(double[])
D:\home\dsimcha\customd\scid\storage\arrayview.d(117): Error: template instance std.typecons.RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1).RefCounted.__ctor!(double[]) error instantiating
D:\home\dsimcha\customd\scid\vector.d(87):        instantiated from here: __ctor!(double[])
D:\home\dsimcha\customd\scid\vector.d(164):        instantiated from here: __ctor!(double[])
D:\home\dsimcha\customd\scid\matrix.d(509):        instantiated from here: opSliceAssign!(double[])
D:\home\dsimcha\bin\test.d(6):        instantiated from here: opIndexAssign!(double[])
D:\home\dsimcha\customd\scid\vector.d(87): Error: template instance scid.storage.arrayview.BasicArrayViewStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1),cast(ArrayViewType)0,vectorType).BasicArrayViewStorage.__ctor!(double[]) error instantiating
D:\home\dsimcha\customd\scid\vector.d(164):        instantiated from here: __ctor!(double[])
D:\home\dsimcha\customd\scid\matrix.d(509):        instantiated from here: opSliceAssign!(double[])
D:\home\dsimcha\bin\test.d(6):        instantiated from here: opIndexAssign!(double[])
D:\home\dsimcha\customd\scid\vector.d(164): Error: template instance scid.vector.BasicVector!(BasicArrayViewStorage!(RefCounted!(CowMatrix!(double,order_),cast(RefCountedAutoInitialize)1),cast(ArrayViewType)0,vectorType)).BasicVector.__ctor!(double[]) error instantiating
D:\home\dsimcha\customd\scid\matrix.d(509):        instantiated from here: opSliceAssign!(double[])
D:\home\dsimcha\bin\test.d(6):        instantiated from here: opIndexAssign!(double[])

**Comment by cristicbz** [comment]
Fixed it using the vectorType argument of ExternalView.
