### ISSUE TITLE
Need a way to print CowMatrix

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#4]
CowMatrix apparently doesn't have a toString() and can't be printed directly.  This may technically be an enhancement request, but it's a pretty annoying limitation.

```
import scid.matrix, scid.ops.eval, std.stdio;

void main() {
    auto foo = Matrix!double([[1.0, 2, 3], [4.0, 5, 6], [7.0, 8, 9]]);
    writeln(foo.toString());  // Doesn't work because foo doesn't have a toString method.
}
```

**Comment by cristicbz** [comment]
You're right there should be a list-of-lists kind of printing. For now you can use writeln(foo.pretty), which prints the matrix formatted somewhat nicely.

**Comment by dsimcha** [comment]
On 7/24/2011 6:32 PM, cristicbz wrote:

> You're right there should be a list-of-lists kind of printing. For now you can use writeln(foo.pretty), which prints the matrix formatted somewhat nicely.

Well, if you have something better in mind as a todo then that's fine, 
but IMHO .pretty works well enough that it can just be the default 
.toString.

**Comment by cristicbz** [comment]
Added toString() that converts the matrix the same way as double[][] gets converted by to!string. I think it's important to have toString() not contain newlines, that's why I don't think pretty should be default.
