### ISSUE TITLE
Excessively strict bounds checking

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#47]
The following code causes assert failures with SciD vectors even though with D arrays it's legal even w/ bounds checking enabled and produces an empty array:

```
import scid.matvec;

void main() {
    auto v = Vector!double(1);
    v[0..0];
}
```

**Comment by cristicbz** [comment]
There is no proper support for zero size matrices & vectors right now, but I was working on fixing this. I was also in the process of replacing all index & slicing checks with some helper functions (checkBounds_, checkSliceIndices_ etc.). This will avoid all the code repetition that is currently present in the form of assert( start <= end && end <= length, sliceMsg_( start, end ) ); etc.
This issue should get fixed once I commit these changes.

**Comment by cristicbz** [comment]
Ok, I've finished the support for zero matrices which also fixes this.
