### ISSUE TITLE
Vector should be a random-access range

### ISSUE THREAD

**Issue by MaksimZh** [cristicbz/scid#48]
Vector should be a random-access range, but it is not:

<pre>
    assert(isInputRange!(Vector!double));         // OK
    assert(isForwardRange!(Vector!double));       // fails
    assert(isBidirectionalRange!(Vector!double)); // fails
    assert(isRandomAccessRange!(Vector!double));  // fails
</pre>

It does not provide "save" member which is required for forward ranges:
http://www.digitalmars.com/d/2.0/phobos/std_range.html#isForwardRange

**Comment by cristicbz** [comment]
Fixed: https://github.com/cristicbz/scid/commit/5b7923e654dfa91ca4063bf0891eec5c8d899f42
