### ISSUE TITLE
Matrix slice-slice-assign ends up transposed

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#50]
```
import scid.matvec, std.stdio;

void main() {
    auto a = matrix([[1.0, 2], [4.0, 5]]);
    auto b = Matrix!double(3, 3);
    b[0..2][0..2] = a;
    writeln(b.pretty);  // Ends up transposed.
}
```

**Comment by cristicbz** [comment]
Grrr, this is almost certainly a regression... Unfortunately, because of OPTLINK it's pretty hard to have a comprehensive test suite to run every time. So testing usually involves copying unittests into main() manually and running them individually.
I'll have to either switch to linux, or to have a number of small test modules, that get individually compiled and run by a script.

**Comment by dsimcha** [comment]
If you have a decent dev box but prefer Windows for day-to-day use, I'd be
inclined to just run Linux in a VM, just for testing code.  That's what I do
at home (at work I use Linux a little more actively).  It works well for me.

**Comment by cristicbz** [comment]
I tried doing that a few times in the past, but with mixed results,
what virtualization software do you use?

---

Cristi Cobzarenco
BSc in Artificial Intelligence and Computer Science
University of Edinburgh
Profile: http://www.google.com/profiles/cristi.cobzarenco

On 17 August 2011 19:01, dsimcha
reply@reply.github.com
wrote:

**Comment by dsimcha** [comment]
I use VMWare player and have used VirtualBox before.  It works reasonably
well for me on both my ancient (4 years old, dual-core AMD) desktop and my
uber-cheap (single-core Celeron w/o hardware virtualization) laptop.  I
think virtualization software has improved a pretty lot in the past few
years.  Any hardware that's not ridiculously ancient or a netbook should
probably run at least 32-bit Linux on top of Windows in a VM reasonably
well.  (64-bit Linux means you need hardware virtualization support for it
to work at all.)

**Comment by cristicbz** [comment]
Fixed, stupid mistake - swapped two if-branches with each other without changing the condition...
