### ISSUE TITLE
Inverting scalars

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#52]
inv(scalar) should compile because it appears in degenerate cases of matrix formulas, etc.

```
import scid.matvec, std.stdio;

void main() {
    double a = 5;
    writeln(eval(inv(a)));
}
```

D:\home\dsimcha\bin\test.d(5): Error: template scid.matrix.inv(M) if (closureOf!(M) == Closure.Matrix) does not match any function template declaration
D:\home\dsimcha\bin\test.d(5): Error: template scid.matrix.inv(M) if (closureOf!(M) == Closure.Matrix) cannot deduce template function from argument types !()(double)

**Comment by cristicbz** [comment]
Added: https://github.com/cristicbz/scid/commit/7e15db28686f5e692d49269ca63fdac1dfc0a26d
