### ISSUE TITLE
Transposing Eagerly Copies

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#61]
Not sure what the best way to do this within the existing design is, but I need to be able to efficiently transpose a matrix without performing any other operation or doing any copying for some of the linalg stuff I'm working on.

```
void main() {
    import scid.matvec, std.stdio;
    auto mat = Matrix!double([[1, 2], [3, 4]]);
    auto mat2 = eval(mat.t);
    writeln(mat.cdata, '\t', mat2.cdata);  // Different addresses
}
```

**Comment by cristicbz** [comment]
It was due to an oversight and a typo - since I'm checking stuff with __traits(compiles,...) some branches get skipped on typos. The latest commit should fix it.
