### ISSUE TITLE
CowMatrix.RefCounted

### ISSUE THREAD

**Issue by dsimcha** [cristicbz/scid#72]
```
import scid.storage.generalmatview, scid.storage.cowmatrix, scid.storage.external,
    scid.matrix;

alias BasicGeneralMatrixViewStorage!(
    ExternalMatrix!( double, StorageOrder.ColumnMajor,
        CowMatrixRef!double)
) Stuff;
```

D:\customd\scid\storage\generalmat.d(220): Error: no property 'RefCounted' for type 
'const(CowMatrix!(double,transposeStorageOrder))'

This only happens on the 2.057 beta, so I initially thought it was a compiler regression.  However, when I looked at the code, tried to reduce it, etc., I realized I have no idea where RefCounted is coming from or how this ever worked on older compiler releases.

**Comment by dsimcha** [comment]
Ok, now I see that the root of the problem isn't what I thought.  The problem is that BasicGeneralMatrixStorage shouldn't be getting instantiated with CowMatrix, not that CowMatrix should have a RefCounted member.  I'll work on this some more tonight.

**Comment by cristicbz** [comment]
Yes, BasicGeneralMatrix should only get instantiatied with CowMatrixRef which is an alias for RefCounted!CowMatrix. I'll try  to get the dmd HEAD to see if I can reproduce it.

**Comment by cristicbz** [comment]
Hmm, I can't seem to reproduce it. Need to check my dmd stack, will take a bit more time.

**Comment by dsimcha** [comment]
I think the problem is that there's been a slight change in the way alias this works.  Now, TransposedOf!(RefCounted!(CowMatrix)) becomes CowMatrix.

```
template TransposedOf( T ) {
    static if( is( T.Transposed ) )
        alias T.Transposed TransposedOf;
    else static if( is( T E : RefCounted!(E,x), uint x ) ) {
        alias RefCounted!(TransposedOf!E,cast(RefCountedAutoInitialize)x) TransposedOf;
    } else static assert( false, T.stringof ~ " has no transpose." );
}
```

I think in 2.056, RefCounted!(CowMatrix).Transposed didn't exist.  Now that alias this works better, things get forwarded and RefCounted!(CowMatrix).Transposed == CowMatrix.Transposed, which is wrong.  I'm not at my dev box now, but probably if you just looked for RefCounted first and then looked for T.Transposed, everything would work.

**Comment by dsimcha** [comment]
Ok, I've set up the relevant stuff on the box I'm currently working on.  Sure enough:

```
import std.typecons;

struct Struct(T) {
    alias T U;
}

template GetU(T) {
    alias T.U GetU;
}

pragma(msg, GetU!(RefCounted!(Struct!double)));
```

2.057 Beta:

double

2.056:

test.d(8): Error: alias test.GetU!(RefCounted!(Struct!(double))).GetU cannot alias an expression double
test.d(11): Error: template instance test.GetU!(RefCounted!(Struct!(double))) error instantiating
test.d(11): Error: undefined identifier T.U

Looks like a bug in alias this got fixed and SciD was inadvertently relying on it.

**Comment by cristicbz** [comment]
That sounds perfectly reasonable, that bugfix actually means there's a few constructs that will be obsolete now (ArrayTypeOf and a few other), but I've been struggling for a few hours and I still can't reproduce it. When I manage to, I'll submit a pull request with the obsolete constructs removed, until then I'm afraid I might commit somehting that doesn't compile with the head.

**Comment by dsimcha** [comment]
You need the latest beta compiler release from ftp.digitalmars.com.  If you cant reproduce it, don't worry about it.  I already know how to fix it and I'll take care of it tonight, along with a few other things I need to fix.

**Comment by dsimcha** [comment]
This one's been fixed for a while.  Closing.
